# Port prefix: 23
version: '3'


networks:
  matrix:


services:

  nginx:
    image: nginx:1.18
    ports:
      - "2380::80"
      - "23443::443"
    volumes:
      - ./site-code:/var/www/html
      - ./services-docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - matrix

  mysql:
    image: mysql:8
    user: 1000:1000
    restart: unless-stopped
    tty: true
    ports:
      - "233306::3306"
    volumes:
      - ./services-docker/db-data:/var/lib/mysql
    networks:
      - matrix
    environment:
      MYSQL_DATABASE: matrix
      MYSQL_USERNAME: matrix
      MYSQL_PASSWORD: k9Hy3lE1inb4
      MYSQL_ROOT_PASSWORD: k9Hy3lE1inb4

  php:
    build:
      context: .
      dockerfile: ./services-docker/php/Dockerfile
    volumes:
      - ./site-code:/var/www/html
      - ./services-docker/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /var/www/html
    user: 1000:1000
    ports:
    - "9000:9000" # Not using port prefix
    depends_on:
      - mysql
    networks:
      - matrix
    environment:
      XDEBUG_CONFIG: remote_host=latitwo
